# Generated by Django 4.2.30 on 2026-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["vendor", "created_at"], name="orders_orde_vendor__d3be3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "created_at"], name="orders_orde_custome_242823_idx"
            ),
        ),
    ]
