# Generated by Django 4.2.30 on 2026-05-15 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bicycle", "Bicycle"),
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("truck", "Truck"),
                        ],
                        default="motorcycle",
                        max_length=20,
                        verbose_name="vehicle type",
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="vehicle number"
                    ),
                ),
                (
                    "vehicle_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="vehicle model"
                    ),
                ),
                (
                    "vehicle_color",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="vehicle color"
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="license number"
                    ),
                ),
                (
                    "license_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="license expiry"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="balance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "driver",
                "verbose_name_plural": "drivers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("license", "Driver License"),
                            ("insurance", "Vehicle Insurance"),
                            ("registration", "Vehicle Registration"),
                            ("identity", "Identity Document"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_number", models.CharField(blank=True, max_length=100)),
                ("file", models.FileField(upload_to="driver_documents/")),
                ("is_verified", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "driver document",
                "verbose_name_plural": "driver documents",
            },
        ),
        migrations.CreateModel(
            name="DriverPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(max_length=50, verbose_name="payout method"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "driver payout",
                "verbose_name_plural": "driver payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriverReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "driver review",
                "verbose_name_plural": "driver reviews",
                "ordering": ["-created_at"],
            },
        ),
    ]
