# Generated by Django 4.2.30 on 2026-05-15 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0001_initial"),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverreview",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_reviews",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="driverpayout",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="drivers.driver",
            ),
        ),
        migrations.AddField(
            model_name="driverdocument",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="drivers.driver",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "driver"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="driverreview",
            unique_together={("driver", "order")},
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["is_available", "is_active"],
                name="drivers_dri_is_avai_07de35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["rating"], name="drivers_dri_rating_0446f8_idx"),
        ),
    ]
