# Generated by Django 4.2.30 on 2026-05-15 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("completed_orders", models.PositiveIntegerField(default=0)),
                ("cancelled_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("new_vendors", models.PositiveIntegerField(default=0)),
                ("new_drivers", models.PositiveIntegerField(default=0)),
                ("products_sold", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "daily analytics",
                "verbose_name_plural": "daily analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="VendorAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_customers", models.PositiveIntegerField(default=0)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "rating_average",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_data",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor analytics",
                "verbose_name_plural": "vendor analytics",
            },
        ),
    ]
