# Generated by Django 4.2.30 on 2026-05-15 10:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=255, verbose_name="shop name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "vendor_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "Restaurant"),
                            ("grocery", "Grocery"),
                            ("pharmacy", "Pharmacy"),
                            ("retail", "Retail"),
                            ("bakery", "Bakery"),
                            ("cafe", "Cafe"),
                            ("other", "Other"),
                        ],
                        default="restaurant",
                        max_length=20,
                        verbose_name="vendor type",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendor_logos/",
                        verbose_name="logo",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="vendor_covers/",
                        verbose_name="cover image",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="state/province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="US", max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("is_open", models.BooleanField(default=True, verbose_name="is open")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="is verified"),
                ),
                (
                    "working_hours",
                    models.JSONField(
                        default=dict,
                        help_text='Format: {"monday": {"open": "09:00", "close": "22:00"}, ...}',
                        verbose_name="working hours",
                    ),
                ),
                (
                    "delivery_radius",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="delivery radius (km)",
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="minimum order amount",
                    ),
                ),
                (
                    "delivery_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="delivery fee",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="tax rate (%)",
                    ),
                ),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        default=30, verbose_name="average preparation time (minutes)"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        limit_choices_to={"role": "vendor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_vendors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor",
                "verbose_name_plural": "vendors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VendorStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("manager", "Manager"),
                            ("cashier", "Cashier"),
                            ("chef", "Chef"),
                            ("delivery_coordinator", "Delivery Coordinator"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("can_manage_orders", models.BooleanField(default=False)),
                ("can_manage_products", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "staff"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor staff",
                "verbose_name_plural": "vendor staff",
                "unique_together": {("vendor", "user")},
            },
        ),
        migrations.CreateModel(
            name="VendorReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="vendors.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "vendor review",
                "verbose_name_plural": "vendor reviews",
                "ordering": ["-created_at"],
                "unique_together": {("vendor", "customer")},
            },
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["is_active", "is_open"], name="vendors_ven_is_acti_d5e939_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                fields=["vendor_type"], name="vendors_ven_vendor__c9b79e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["city"], name="vendors_ven_city_4e1b89_idx"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["rating"], name="vendors_ven_rating_1e84ed_idx"),
        ),
    ]
